### ISSUE TITLE
Wait until kafka_cluster is ready after create

### ISSUE THREAD

**Issue by Mongey** [Mongey/terraform-provider-confluentcloud#18]
```
{
  "clusters": [
    {
....
      "status": "UP",
...
```

**Comment by j-tim** [comment]
Is there any update on this issue? It will be great to be able to provision a Kafka cluster and create some topics in one go.

**Comment by Mongey** [comment]
@j-tim Yeah, this was released in `v0.0.7` ... I found the `status` value from the api to unreliable, and had the provider connect to the cluster to check availability.

**Comment by j-tim** [comment]
Hi, @Mongey thanks for your quick response. That's great I will give try to provision a Kafka cluster and create some topics in one go with the latest versions.
