### ISSUE TITLE
Please release new version with schema registry resource included

### ISSUE THREAD

**Issue by askoriy** [Mongey/terraform-provider-confluentcloud#46]
With Terraform 0.13 the preferred way to use the module is Terraform Registry, but the last available version v0.0.5 has no resource "confluentcloud_schema_registry". Please make a new release to include schema registry resource.

**Comment by Mongey** [comment]
[`v0.0.6`](https://github.com/Mongey/terraform-provider-confluentcloud/releases/tag/v0.0.6)
