### ISSUE TITLE
What args goes into provider? 

### ISSUE THREAD

**Issue by skyzhou0** [Mongey/terraform-provider-confluentcloud#53]
The current terraform version is 0.12.13

getting an error: "An argument named "CONFLUENT_CLOUD_USERNAME" is not expected here.

**Comment by Mongey** [comment]
`username` and `password`.

```hcl
provider "confluentcloud" {
   username = "ccloud@example.org"
   password = "hunter2"
 }
```
I've updated the readme to show an example
https://github.com/Mongey/terraform-provider-confluentcloud/commit/4a0730d4e79f7dc6747a0584ddb13547442804ce

**Comment by skyzhou0** [comment]
perfect. thank you
