### ISSUE TITLE
Error : InternalValidate - Release v0.0.8

### ISSUE THREAD

**Issue by prabhakarank87** [Mongey/terraform-provider-confluentcloud#68]
@Mongey, Getting the below error when use the new release v0.0.8. could you please take a look ?

---
Error: InternalValidate

Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource confluentcloud_kafka_cluster: deployment: TypeMap with Elem
*Resource not supported,use TypeList/TypeSet with Elem *Resource or TypeMap
with Elem *Schema

**Comment by prabhakarank87** [comment]
@Mongey , Did you get a chance to look into this issue ?

**Comment by Mongey** [comment]
Will check this out later today, Could be an issue with updating to the new terraform sdk.

**Comment by prabhakarank87** [comment]
Thanks @Mongey. Could you please create the new release for that. so that i can test the same

**Comment by Mongey** [comment]
@prabhakarank87 released v0.0.9
