### ISSUE TITLE
Enhancement request - support creation and management of the SQL cdc connector

### ISSUE THREAD

**Issue by Marcus-James-Adams** [Mongey/terraform-provider-confluentcloud#70]
It would be really useful if it would be possible to setup/manage the SQL cdc connector that confluent cloud pride via this provider.

**Comment by sv3ndk** [comment]
Hi Marcus,
I'm unrelated to this repo, although I understand the support or connectors is now implemented and merged to master:
https://github.com/Mongey/terraform-provider-confluentcloud/pull/82
It's not been bundled in a release yet though (see also discussion in the thread above)

**Comment by Mongey** [comment]
This is released in [v0.0.11](https://github.com/Mongey/terraform-provider-confluentcloud/releases/tag/v0.0.11)
