### ISSUE TITLE
Update github.com/cgroschupp/go-client-confluent-cloud to suppress debug logging

### ISSUE THREAD

**Issue by raytung** [Mongey/terraform-provider-confluentcloud#88]
Hey :wave: 

It would be awesome to update the [github.com/cgroschupp/go-client-confluent-cloud](github.com/cgroschupp/go-client-confluent-cloud) dependency when / if this PR lands https://github.com/cgroschupp/go-client-confluent-cloud/pull/22. That PR allows configuring debug logging for the Confluent client, which at the moment is hard coded to `true`.

Cheers

**Comment by Mongey** [comment]
Thanks @raytung  I'll pull it in when it gets merged.

**Comment by treykasada** [comment]
Hey @Mongey, sorry to be a pain, but is there any ETA on a release for this change? 😇

**Comment by Mongey** [comment]
Released in [v0.0.12](https://github.com/Mongey/terraform-provider-confluentcloud/releases/tag/v0.0.12)

**Comment by treykasada** [comment]
Thanks my dude! ❤️
