### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by bpb54321** [Mongey/terraform-provider-confluentcloud#90]
Hi there, I was wondering when you are going to release 0.11? I would really like to use the Confluent Cloud Connector feature that was merged into master 15 days ago. The release 0.10 was release ~ 2 months ago, so it doesn't include the Confluent Cloud Connector feature.

**Comment by Mongey** [comment]
See my comment https://github.com/Mongey/terraform-provider-confluentcloud/pull/82#issuecomment-873221290
> I noticed the acceptance tests fail, as there's no topic for test-datagen-data. I'll need to fix that before cutting a new release.

**Comment by bpb54321** [comment]
@Mongey Thanks for your note! Do you have an estimated time frame to fix the acceptance tests and cut a new release? I have to manually clone the repo to use the Confluent Cloud Connector feature until a new release is cut. Thanks again for putting this provider together, it's quite nice!

**Comment by Mongey** [comment]
https://github.com/Mongey/terraform-provider-confluentcloud/releases/tag/v0.0.11

**Comment by bpb54321** [comment]
Thanks so much!
